### ISSUE TITLE
It would be so amazing if your tool could be used to transfer Stadia savegames

### ISSUE THREAD

**Issue by tmueller78** [PapaElGunmen/Sekiro-Save-Organizer#4]
Hi @Asiern, 

I'm currently trying to transfer my savegame from Stadia to Steam as Stadia is closing down on Jan 18th.
I discovered your tool and saw that you figured out how to manipulate the sl2-files.
When downloading the savegames from the stadia version, one gets this:
![image](https://user-images.githubusercontent.com/3420501/209482249-bf74568d-cc00-462f-a129-2c5278441c7d.png)

As the steam version uses *.sl2 files, which seems to be a container for savefiles, my current hope with your project is that that's the same file format as used within the sl2 files. I'll attach my set in case you have the time to try it out by chance.

Best regards

Tobias

[Sekiro™_ Shadows Die Twice_1000_gamesave.zip](https://github.com/Asiern/Sekiro-Save-Organizer/files/10300645/Sekiro._.Shadows.Die.Twice_1000_gamesave.zip)

**Comment by Asiern** [comment]
Hi @tmueller78,

I have taken a look to your savefiles and stadia takes a different aproach on how saves are stored (compared to pc). Stadia might encrypt the saves (or something like that).  So after giving it an initial look, **it seems that stadia and pc savefiles are not compatible** between them, without processing (or converting) the savefile (decryption, uncomprerssion...).

The goal of this tool is to create copies of the current savefile of the game. This way, you can have multiple states of the game stored for future use. It does not manipulate the content of the savefile in any way.

Besides that, some of your saves are just a bunch of `00` (in binary) repeated. So, I'm supposing that some of your saves are empty or corrupted (for example `userdata0001`).

**Comment by tmueller78** [comment]
Dear @Asiern,

thanks for the fast turnaround! Looks like I have quite something to do for the next couple of weeks. The situation is similar for Shadow of the Tomb Raider and Doom Eternal, in which, as with Sekiro, I'm too far in for my taste to start from scratch. 

Best regards

Tobias
